{
 "title": "Netdata Memory Drilldown",
 "tags": [
  "netdata",
  "drilldown",
  "memory"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(netdata_info, job)"
   },
   {
    "name": "instance",
    "label": "Machine",
    "query": "label_values(netdata_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\",dimension=\"used\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(\n  netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\",dimension!=\"used\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average memory consumption",
   "type": "table",
   "gridPos": { "h": 20, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  netdata_apps_mem_MiB_average{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "committed memory / page faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "mbytes", "label": "committed memory" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_mem_committed_MiB_average{job=~\"$job\",instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(netdata_mem_pgfaults_faults_persec_average{job=~\"$job\",instance=\"$instance\"})",
     "legendFormat": "page faults"
    }
   ]
  },
  {
   "title": "application memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  netdata_apps_mem_MiB_average{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "dirty memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_mem_writeback_MiB_average{job=\"$job\",instance=\"$instance\",dimension=\"Dirty\"})",
     "legendFormat": "dirty memory"
    }
   ]
  }
 ]
}