global:
  scrape_interval: 5s

scrape_configs:
- job_name: netdata
  metrics_path: '/api/v1/allmetrics'
  params:
    format: ['prometheus']
  static_configs:
  - targets:
    - 'netdata:19999'
  relabel_configs:
  - target_label: instance
    regex: '(.+):.*'
    source_labels: [__address__]
