{
 "title": "Netdata Machine Drilldown",
 "tags": [
  "netdata",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Machine",
    "query": "label_values(netdata_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)"
    }
   ]
  },
  {
   "title": "total system memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "system uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_swap_MiB_average{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "total mounted storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_disk_space_GiB_average{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "cgroups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\n  count(\n    netdata_cgroup_cpu_percent_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)"
    }
   ]
  },
  {
   "title": "CPU usage / type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_system_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"})"
    }
   ]
  },
  {
   "title": "average memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\",dimension=\"used\"})\n/\nsum(netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\"})\n* 100"
    }
   ]
  },
  {
   "title": "CPU usage / application",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_apps_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n) by (dimension)\n/\nignoring (dimension) group_left\ncount(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\",dimension=\"used\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(\n  netdata_system_ram_MiB_average{job=~\"$job\",instance=\"$instance\",dimension!=\"used\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "load avg / 5min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "netdata_system_load_load_average{job=\"$job\",instance=\"$instance\",dimension=\"load5\"}"
    }
   ]
  },
  {
   "title": "load avg / 15min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "netdata_system_load_load_average{job=\"$job\",instance=\"$instance\",dimension=\"load15\"}"
    }
   ]
  },
  {
   "title": "traffic bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(\n  abs(\n    netdata_net_net_kilobits_persec_average{job=\"$job\",instance=\"$instance\",dimension=\"sent\"}\n  )\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(\n  abs(\n    netdata_net_net_kilobits_persec_average{job=\"$job\",instance=\"$instance\",dimension=\"received\"}\n  )\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "disk operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  abs(\n   netdata_disk_ops_operations_persec_average{job=~\"$job\",instance=\"$instance\",dimension=\"reads\",family!~\".*/.*\"}\n  )\n) by (family)",
     "legendFormat": "reads from {{ family }}"
    },
    {
     "expr": "sum(\n  abs(\n    netdata_disk_ops_operations_persec_average{job=\"$job\",instance=\"$instance\",dimension=\"writes\",family!~\".*/.*\"}\n  )\n) by (family)",
     "legendFormat": "writes to {{ family }}"
    }
   ]
  },
  {
   "title": "mount capacity",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum (\n  netdata_disk_space_GiB_average{job=\"$job\",instance=\"$instance\",dimension=\"used\",family!~\"(/boot|/dev|/run|/host)($|/.+)\"}\n) by(family)\n/\nsum (\n  netdata_disk_space_GiB_average{job=\"$job\",instance=\"$instance\"}\n) by(family)"
    }
   ]
  }
 ]
}