{
 "title": "Netdata CPU Drilldown",
 "tags": [
  "netdata",
  "drilldown",
  "cpu"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Machine",
    "query": "label_values(netdata_info{job=\"$job\"}, instance)"
   },
   {
    "name": "netdata_cpu_core",
    "label": "Netdata CPU core",
    "query": "label_values(netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}, chart)"
   }
  ]
 },
 "panels": [
  {
   "title": "average CPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"})"
    }
   ]
  },
  {
   "title": "load average (5m)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "netdata_system_load_load_average{job=\"$job\",instance=\"$instance\",dimension=\"load5\"}"
    }
   ]
  },
  {
   "title": "core load distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n) by (chart)",
     "legendFormat": "{{ chart }}"
    }
   ]
  },
  {
   "title": "system / user load distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_apps_cpu_system_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n)\n/\nignoring (dimension) group_left\ncount(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)",
     "legendFormat": "system"
    },
    {
     "expr": "sum (\n  netdata_apps_cpu_user_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n)\n/\nignoring (dimension) group_left\ncount(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "load average (15m)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "netdata_system_load_load_average{job=\"$job\",instance=\"$instance\",dimension=\"load15\"}"
    }
   ]
  },
  {
   "title": "average iowait share",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension=\"iowait\"})\n/\nsum(netdata_system_cpu_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"})\n* 100"
    }
   ]
  },
  { "title": "task utilization per core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$netdata_cpu_core",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "repeat": "netdata_cpu_core",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\",chart=~\"$netdata_cpu_core\",dimension!=\"idle\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  { "title": "user and system load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "system",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_apps_cpu_system_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n) by (dimension)\n/\nignoring (dimension) group_left\ncount(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "user",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_apps_cpu_user_percentage_average{job=\"$job\",instance=\"$instance\",dimension!=\"idle\"}\n) by (dimension)\n/\nignoring (dimension) group_left\ncount(\n  count(\n    netdata_cpu_cpu_percentage_average{job=\"$job\",instance=\"$instance\"}\n  ) by (chart)\n)",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  { "title": "interrupts, softirqs, softnets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "interrupts per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_cpu_interrupts_interrupts_persec_average{job=\"$job\",instance=\"$instance\"}\n) by (chart)",
     "legendFormat": "{{ chart }}"
    }
   ]
  },
  {
   "title": "softirqs per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_cpu_softirqs_softirqs_persec_average{job=\"$job\",instance=\"$instance\"}\n) by (chart)",
     "legendFormat": "{{ chart }}"
    }
   ]
  },
  {
   "title": "softnet events per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  netdata_cpu_softnet_stat_events_persec_average{job=\"$job\",instance=\"$instance\"}\n) by (chart)",
     "legendFormat": "{{ chart }}"
    }
   ]
  }
 ]
}